<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /* @var $block \Magento\Catalog\Block\Product\View\AbstractView */?>
<?php 
$_product = $block->getProduct();
$helper = $this->helper('Abhay\EnhanceStore\Helper\Data');
$enable = $helper->isModuleEnabled();
$spEnabled = $helper->isSpEnabled();
$spSalableEnabled = $helper->isSpSalableEnabled();
$sku = $_product->getSku();
$pqty=0;
$product=$block->getSaleble($sku);
foreach ($product as $qty) {
    if($qty['qty']){
        $pqty=$qty['qty'];
    }
}
?>
<?php
 if($enable && $spEnabled && $spSalableEnabled){
    echo "<br/><b>Now Left only: </b>" .$pqty;
 }  
 ?>
<?php if ($block->displayProductStockStatus()) :?>
    <?php if ($_product->isAvailable()) :?>
        <div class="stock available" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
            <span><?= $block->escapeHtml(__('In stock')) ?></span>
        </div>
    <?php else :?>
        <div class="stock unavailable" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
            <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
        </div>
    <?php endif; ?>
<?php endif; ?>
